name: Build Pong App

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      NGINX_HTTP_PORT: ${{ secrets.NGINX_HTTP_PORT }}
      NGINX_HTTPS_PORT: ${{ secrets.NGINX_HTTPS_PORT }}

    steps:
    - uses: actions/checkout@v6

    - name: Prepare env files
      run: |
        cp .env.example .env
        cp api-gateway/.env.example api-gateway/.env
        cp services/game-service/.env.example services/game-service/.env
        cp services/user-service/.env.example services/user-service/.env

    - name: Build and run containers
      run: make up
      
   #Test: Show that environment variables are working
    - name: Print environment variables
      run: |
       if [ -z "$POSTGRES_USER" ]; then
       echo "POSTGRES_USER not set"
       exit 1
       fi
       echo "All required secrets are set"

    - name: Wait for API Gateway #without this tests might run before services are ready
      run: |
        echo "Waiting for API Gateway..."
        for i in {1..30}; do
          if curl -s http://localhost:3000 >/dev/null; then
            echo "API Gateway is up"
            exit 0
          fi
          sleep 2
        done
        echo "API Gateway did not start"
        docker compose logs
        exit 1

    - name: Run user-service register tests
      run: |
        chmod +x init-scripts/test-scripts/user-service/register.sh
        ./init-scripts/test-scripts/user-service/register.sh

    - name: Run user-service login tests
      run: |
        chmod +x init-scripts/test-scripts/user-service/login.sh
        ./init-scripts/test-scripts/user-service/login.sh

    - name: Dump logs on failure
      if: failure()
      run: docker compose logs
    


