name: Build Pong App

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      NGINX_HTTP_PORT: ${{ secrets.NGINX_HTTP_PORT }}
      NGINX_HTTPS_PORT: ${{ secrets.NGINX_HTTPS_PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}

    steps:
    - uses: actions/checkout@v6

    - name: Prepare env files
      run: |
        cp .env.example .env
        cp api-gateway/.env.example api-gateway/.env
        cp services/game-service/.env.example services/game-service/.env
        cp services/user-service/.env.example services/user-service/.env

    - name: Build and run containers
      run: |
        docker compose down -v || true
        docker compose build --no-cache
        docker compose up -d

   #Test: Show that environment variables are working
    - name: Print environment variables
      run: |
       if [ -z "$POSTGRES_USER" ]; then
       echo "POSTGRES_USER not set"
       exit 1
       fi
       echo "All required secrets are set"


    - name: Run user-service register tests
      run: |
        chmod +x init-scripts/test-scripts/user-service/register.sh
        ./init-scripts/test-scripts/user-service/register.sh

    - name: Run user-service login tests
      run: |
        chmod +x init-scripts/test-scripts/user-service/login.sh
        ./init-scripts/test-scripts/user-service/login.sh

    - name: Run user-service signout tests
      run: |
        chmod +x init-scripts/test-scripts/user-service/signout.sh
        ./init-scripts/test-scripts/user-service/signout.sh

    - name: Run game-service running tests
      run: |
       chmod +x init-scripts/test-scripts/game-service/game-running.sh
       ./init-scripts/test-scripts/game-running.sh

    - name: Run game-service reset tests
      run: |
       chmod +x init-scripts/test-scripts/game-reset.sh
       ./init-scripts/test-scripts/game-service/game-reset.sh

    - name: Dump logs on failure
      if: failure()
      run: docker compose logs

    # - name: Run user-service update tests ---- not working in CI environment due to cookies being actually reliable for browsers and not CI
    #   run: |
    #     chmod +x init-scripts/test-scripts/user-service/update.sh
    #     ./init-scripts/test-scripts/user-service/update.sh

    - name: Run user-service signout tests
      run: |
        chmod +x init-scripts/test-scripts/user-service/signout.sh
        ./init-scripts/test-scripts/user-service/signout.sh

    - name: Dump logs on failure
      if: failure()
      run: docker compose logs



